### PR TITLE
DatetimeField Error Handling Enhancement

### PR DESCRIPTION
**Pull request by hchamorro**
It enhances user feedback when a user is typing a date.
It introduces a new error when user is typing date and is incorrect format.
It correctly handles prop drilling and prioritization of errorText and errors.

### **PR Type**
enhancement, bug fix

___

### **Description**
- Introduced `errorText` prop to allow external error messages to be displayed in the `DateTimeField` component.
- Improved error handling by using a `localError` state to manage error messages internally.
- Enhanced placeholder logic to provide appropriate format hints based on the `type` of date/time being used.
- Refactored the component to ensure error messages are displayed correctly and consistently.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DateTimeField.tsx</strong><dd><code>Enhanced error handling and placeholder logic in DateTimeField</code></dd></summary>
<hr>

packages/ui/src/DateTimeField.tsx

<li>Added <code>errorText</code> prop to handle external error messages.<br> <li> Improved error handling with <code>localError</code> state.<br> <li> Enhanced placeholder logic for different date/time types.<br> <li> Refactored to ensure error messages are displayed correctly.<br>

</details>

  </td>
  <td><a href="https://github.com/FlourishHealth/ferns-ui/pull/715/files#diff-bea8f5eb9bb3d85082ea2444cd9e7ddf5333cd199bcb204f64da2e8056c11f9e">+32/-19</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by joshgachnang** [comment]
@hchamorro can you write a PR description?

**Review by joshgachnang — APPROVED** [review]
Approved, I got the context for the PR from Slack. But in the future, please don't put in blank PRs

**Review by abbiecoghlan — APPROVED** [review]

**Comment by hchamorro** [comment]
> Approved, I got the context for the PR from Slack. But in the future, please don't put in blank PRs

yep totally my bad, it was 2:57 and i defiantly spazzed was trying to get it in before the next stand up alert

**Comment by joshgachnang** [comment]
Hahah all good!

**Pull request merged**
