### PR TITLE
Add a checkbox option to the multiselect

### PR DESCRIPTION
**Pull request by swanka**
Screenshot 2023-01-26 at 9 34 55 AM

### CODE REVIEW

**Review by joshgachnang — COMMENTED** [review]
The code looks reasonable! What's the driving reason here? I'd love to keep ferns opinionated and only have toggles or checkboxes. And checkboxes seem quite a bit more common.

**Comment by swanka** [comment]
> The code looks reasonable! What's the driving reason here? I'd love to keep ferns opinionated and only have toggles or checkboxes. And checkboxes seem quite a bit more common.

I'd honestly be ok with removing the toggles. Wasn't sure if someone wanted to keep the toggles around though.

**Comment by joshgachnang** [comment]
@kjkurtz any thoughts here? I think I threw this in as a quick hack to get multi select working.

**Comment by kjkurtz** [comment]
I think that multiselect pretty much always means checkboxes to me as well. The toggles are a bit confusing for any multiselect use case I can think of or find in our code currently.

So if it were up to me, I'd get rid of toggles for multiselect and just have checkboxes. Save toggles for more of an 'on/off' scenario.

**Comment by joshgachnang** [comment]
Sounds good to me, let's remove the toggles and only support checkboxes.

**Review by joshgachnang — APPROVED** [review]
Nice, looks great!

**Pull request merged**
